"""Roles to array

Revision ID: 1ba1bf5c902d
Revises: 170a05743ad2
Create Date: 2022-06-30 20:26:45.762474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ba1bf5c902d'
down_revision = '170a05743ad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.add_column('users', sa.Column(
        'roles', sa.ARRAY(sa.String), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.add_column('users', sa.Column('roles', sa.String(), nullable=True))
    # ### end Alembic commands ###
