"""Sections & tags

Revision ID: 37c5cb45e29b
Revises: a8a8944b04a0
Create Date: 2022-07-03 01:10:23.373827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37c5cb45e29b'
down_revision = 'a8a8944b04a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('section', sa.String(), nullable=True))
    op.add_column('posts', sa.Column(
        'tags', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'tags')
    op.drop_column('posts', 'section')
    # ### end Alembic commands ###
