"""Hotfix datatype

Revision ID: a8a8944b04a0
Revises: cbdec367d532
Create Date: 2022-06-30 22:13:31.280970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8a8944b04a0'
down_revision = 'cbdec367d532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'liked_by')
    op.add_column('posts', sa.Column(
        'liked_by', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'liked_by')
    op.add_column('posts', sa.Column(
        'liked_by', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###
