"""Added required tables v2

Revision ID: f6e2a9028f2e
Revises: d5f540524f29
Create Date: 2022-06-30 01:43:53.612890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e2a9028f2e'
down_revision = 'd5f540524f29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('status', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('users_ids', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('posts', sa.Column('views', sa.Integer(), nullable=True))
    op.drop_constraint('posts_user_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'user_id')
    op.add_column('users', sa.Column('posts_ids_owned', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'posts_ids_owned')
    op.add_column('posts', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('posts_user_id_fkey', 'posts', 'users', ['user_id'], ['id'])
    op.drop_column('posts', 'views')
    op.drop_column('posts', 'users_ids')
    op.drop_column('posts', 'status')
    op.drop_column('posts', 'likes')
    op.drop_table('comments')
    # ### end Alembic commands ###
